boostcampwm-2024/web28-DDara

- .github/workflows/auto-assign-reviewers.yml
- .github/workflows/auto-merge.yml
- .github/workflows/ci.yml
- .github/workflows/request-changes.yml
- PR 생성시 리뷰어 2명 자동 설정 로직
- Reviewer 2명이 리뷰를 남기고 승인한 뒤, 라벨이 "작업 완료"로 변경되고 자동으로 특정 브랜치에 Merge하는 로직
- Lint, Build, Test 검사해서 오류가 있는지 확인 후 오류 발생 시 워크플로우 실패로 처리
- 리뷰 과정에서 반려될 경우 라벨을 "수정 요청"으로 변경하고 작업자에게 알림 보내기 로직
> [ENV][Chore] #1 : CI/CD를 위한 깃허브 엑션 설정

- frontend/index.html
- frontend/package.json
- pnpm-lock.yaml
- `index.html` 에 네이버 지도 로딩을 위한 코드 추가
- 비동기 통신
- geocoder 모듈 추가 : 고유명칭을 갖고 좌표로 전환하는 모듈 추가
- TS 사용을 위한 Type 추가
- 타입 설정파일 추가 및 지도 로딩을 위한 코드 추가
#107
> [FE][Feat] #107 : 네이버 지도 사용을 위한 로딩 코드 및 Type 추가

- frontend/src/component/Layout/Footer.tsx
- frontend/src/component/Layout/Header.tsx
- frontend/src/component/Layout/Layout.tsx
- frontend/src/component/Layout/enumTypes.ts
- frontend/tailwind.config.js
---
- header, footer로 이루어진 layout component 구현
- 확장성과 보편성을 위해 props로 설정
- tailwind boxshadow 추가
---
---
```
import React, { ReactNode } from 'react';
import { Header } from './Header';
import { Footer } from './Footer';
interface ILayoutProps {
children: ReactNode;
headerTitle?: string;
footerTitle?: string;
isHeaderTransparent?: boolean;
footerActive?: boolean;
headerButton?: ReactNode;
footerOnClick?: () => void;
}
export const Layout: React.FC<ILayoutProps> = ({
children,
headerTitle,
footerTitle,
isHeaderTransparent = false,
footerActive = true,
headerButton,
footerOnClick,
}) => (
<div className="flex flex-col items-center w-full h-full bg-gray-400">
{/* Header */}
<Header title={headerTitle} isTransparency={isHeaderTransparent} buttonElement={headerButton} />
{/* Main content */} …
```
> [FE][FEAT] #134 : Layout Component 구현

- backend/package.json
- backend/src/controllers/channelController.js
- backend/src/index.js
- backend/src/repositories/channelRepository.js
- backend/src/repositories/guestRepository.js
- backend/src/routes/channelRouter.js
- backend/src/services/channelService.js
- eslint.config.mjs
- pnpm-lock.yaml
- uuid 생성을 위한 패키지 설치
- eslint 백엔드 설정 수정
- 채널 생성 api 구현 (router, controller, service, repository)
- guest 추가 api 구현
- postman 테스트
---
- uuid 생성을 위한 패키지 설치
- eslint 백엔드 설정 수정
- 채널 생성 api 구현 (router, controller, service, repository)
- guest 추가 api 구현
- postman 테스트
---
---
#49 
---
---
- request json 예시
```json
{
"name": "Test Channel",
"host_id": "jhi2359",
"guests": [
{
"name": "user1",
"start_location": {"lat": 37.5665, "lng": 126.9780},
"end_location": {"lat": 37.5665, "lng": 127.9780},
"path": [{"lat": 37.5665, "lng": 126.9780}, {"lat": 37.5665, "lng": 126.9780}],
"marker_style": {"color": "red"}
},
{
"name": "user2",
"start_location": {"lat": 37.5650, "lng": 126.9775},
"end_location": {"lat": 37.5750, "lng": 126.9875},
"path": [{"lat": 37.5665, "lng": 126.9780}, {"lat": 37.5665, "lng": …
```
> [BE][Feat] : #49 : 경로방 생성 api

- backend/src/routes/channelRouter.js
- backend/swaggerConfig.js
- login api에 대한 swagger 문서 수정
- channel 생성 api에 대한 swagger 문서 생성
---
- login api에 대한 swagger 문서 수정
- channel 생성 api에 대한 swagger 문서 생성
---
---
#49 
---
> [BE][Feat] : swagger 문서 작성 및 수정

- backend/src/controllers/authController.js
- backend/src/controllers/channelController.js
- backend/src/index.js
- backend/src/repositories/userRepository.js
- backend/src/routes/authRouter.js
- backend/src/routes/channelRouter.js
- backend/src/services/authService.js
- backend/src/services/channelService.js
- backend/swaggerConfig.js
- 회원가입 api에 대한 swagger 문서 추가
- 회원가입 api 구현
- auth에 대한 jsdoc 추가
- 회원가입시 비밀번호 암호화해서 db에 저장
- channel api에 대한 swagger 문서 tag 추가
- controller, service, repository에 대한 jsdoc 추가
- index.js 불필요한 코드 제거
---
- 회원가입 api에 대한 swagger 문서 추가
- 회원가입 api 구현
- auth에 대한 jsdoc 추가
- 회원가입시 비밀번호 암호화해서 db에 저장
- channel api에 대한 swagger 문서 tag 추가
- controller, service, repository에 대한 jsdoc 추가
- index.js 불필요한 코드 제거
---
---
#158 
---
---
> [BE][Feat] #159 : 회원가입 api 구현, [BE][Refactor] swagger 문서 tag 추가, jsdoc 추가

- backend/Dockerfile
- docker-compose.yml
- nginx.conf
- docker-compose 파일 작성
- nginx 파일 작성
- 백엔드 dockerfile 작성
- local 테스트 완료
---
- docker-compose 파일 작성
- nginx 파일 작성
- 백엔드 dockerfile 작성
- local 테스트 완료
---
---
#166 
---
---
root에서 `docker-compose up --build` 명령어 입력시 실행됩니다.
---
> [BE][Chore] #166 : docker-compose, nginx 설정 및 백엔드 dockerfile 작성

- frontend/src/hooks/getUserLocation.ts
- frontend/src/pages/Main.tsx
- 현재 위치를 받아오는 함수 구현
- 현재의 위치를 반환
- 현재의 위치를 반환할 수 없다면 error와 함께 네이버의 위치로 반환
- 메인 페이지 구현
- 지도에 현재 위치를 기준으로 표시
- 바텀시트
- contentData 더미데이터를 추후 분리하거나 백엔드와의 연결로 대체할 예정입니다
> [FE][Feat] #30 : Main 페이지

- .github/workflows/auto-merge.yml
auto-merge 정상적으로 동작안되는 문제 수정
- "확인 요청" 상태에서 Approve가 2명 혹은 3명일 시 자동으로 "확인 요청" 라벨 삭제하고, "작업 완료" 라벨 붙인 후 머지될 수 있도록 수정하였습니다.
- 기존 코드에서 에러가 났던 부분은 각 `step`에서의 `return` 관련된 부분임을 확인을 했고 이를 수정하였습니다.
> [ENV][Fix] #1 : auto-merge 정상적으로 동작안되는 문제 수정

- .github/workflows/auto-assign-reviewers.yml
github action 중 auto assign 버그를 수정하였습니다.
- 이벤트 동작을 opened 인 경우만 처리하도록 했습니다.
```
on:
pull_request:
types: [opened]
```
- 메인 브렌치인지와 dev 브렌치인 경우 리뷰어가 3명이 할당되도록 수정하였습니다.
```
- name: 'Determine Number of Reviewers'
id: determine_reviewers
uses: actions/github-script@v6
with:
script: |
const targetBranch = context.payload.pull_request.base.ref;
const reviewers = targetBranch === 'main' ? 3 : 2;
return { number_of_reviewers: reviewers };
- name: 'Assign Reviewers'
uses: kentaro-m/auto-assign-action@v2.0.0
with:
repo-token: '${{ secrets.GITHUB_TOKEN }}'
configuration-path: '.github/auto_assign_config.yml'
numberOfReviewers: ${{ steps.determine_reviewers.outputs.number_of_reviewers }}
```
> [ENV][Fix] #1 : auto-assign 라벨 바뀔때마다 되는 문제 수정

- frontend/src/component/authmodal/AuthModal.tsx
- frontend/src/component/common/modal/Modal.tsx
- frontend/src/component/common/modal/ModalFooter.tsx
- frontend/src/component/common/modal/ModalHeader.tsx
- frontend/src/component/common/modal/ModalInput.tsx
- frontend/src/hooks/useModal.ts
- frontend/src/stories/AuthModal.stories.tsx
- frontend/src/stories/common/modal/Modal.stories.tsx
- frontend/src/stories/common/modal/ModalFooter.stories.tsx
- frontend/src/stories/common/modal/ModalHeader.stories.tsx
- frontend/src/stories/common/modal/ModalInput.stories.tsx
- 모달 열기 닫기 hook 제작
- 컴포넌트의 common Modal 컴포넌트 구현
- Modal과 같이 다양한 형태가 나올 수 있는 컴포넌트는 합성 방식의 컴포넌트를 사용하였습니다
- Input과 같이 비교적 단순한 형태의 컴포넌트에는 구성 방식의 컴포넌트를 사용하였습니다
- common Modal 컴포넌트를 이용하여 AuthModal 컴포넌트 구현
- type에 따라 login 또는 register 모달창이 되는 컴포넌트입니다.
- 각각의 컴포넌트에 대해 storybook을 작성하였습니다
#59 로그인 모달 창은 ID와 PW를 받을 수 있다.
https://github.com/user-attachments/assets/8b9c8eaf-0d7d-417e-90e6-a54b1a44bc27
[Storybook으로 React 컴포넌트 문서화하기]
(https://velog.io/@jackson5272/Storybook%EC%9C%BC%EB%A1%9C-%EC%BB%B4%ED%8F%AC%EB%84%8C%ED%8A%B8-%EB%AC%B8%EC%84%9C%ED%99%94%ED%95%98%EA%B8%B0)
> [FE][Feat] #59 : AuthModal 컴포넌트

- frontend/src/component/userboard/UserBoard.tsx
- frontend/src/stories/userboard/userboard.stories.tsx
- 지도 페이지 우측 하단 사용자 현황판 구현
- dropdown과 연결해야 하기에 context나 props 정의 전 mock데이터로 구현
- tsDoc 작성
- storybook 작성
---
---
**설명**: 이 체크리스트는 PR 작성자가 스스로 점검할 수 있는 기준을 제시합니다. 코드가 빌드 오류 없이 작동하고, 테스트를 통과하며, 스타일 가이드를 따르고 있는지 확인하는 항목들입니다.
---
#194 
---
---
- 우선 mock데이터로 구현하였습니다!
- 지도 페이지 구현 하여 경로에 따른 user 데이터를 받아오는 작업 완료되면 추후 구현하겠습니다!
> [FE][Feat] #194 : userboard 구현

- frontend/src/component/common/FloatingButton/FloatingButton.tsx
- frontend/src/hooks/useFloatingButton.ts
- frontend/src/pages/Main.tsx
- frontend/src/stories/BottomSheet.stories.tsx
- frontend/src/stories/FloatingButton/Floatingbutton.stories.tsx
- 플로팅 버튼 내부 함수 hook으로 변경
- 인터페이스 정의
- 스토리북 작성
- 폴더명 변경
---
#145 
---
- open과 close state에서는 control 및 action 불가
- toggle state에서 action 가능
---
> [FE][Fix][Docs] #145 : 플로팅 버튼 구조 변경 및 스토리북 추가

- backend/src/index.js
- backend/src/websocketServer.js
- frontend/vite.config.ts
websocket 연결
---
- websocket 연결
- websocket 연결 테스트
---
---
#40
---
[> PR과 관련된 참고 자료가 있다면 링크나 설명을 첨부해주세요.
> 예: "다크 모드 구현을 위한 라이브러리 사용 가이드 링크"](https://velog.io/@happyhyep/WebSocket-%EC%84%9C%EB%B2%84%EC%99%80-HTTP-%EC%84%9C%EB%B2%84-%EB%AC%B8%EC%A0%9C-%ED%95%B4%EA%B2%B0%EA%B8%B0)
> [BE][Feat] #40 : websocket 연결

- eslint.config.mjs
- frontend/package.json
- frontend/src/api/client.api.ts
- frontend/src/api/dto/response.dto.ts
- frontend/src/constants.ts
- frontend/src/pages/Main.tsx
- frontend/src/utils/common/manageLocalData.ts
- pnpm-lock.yaml
공통 함수 세팅
---
- axios 관련 패키지 설치 및 세팅
- localStorage 세팅
- eslint max-classes-per-file 세팅 off
---
---
#193 
---
> [FE][Feat] #193 : 공통 함수 세팅

- frontend/src/component/linedrawer/Linedrawer.tsx
- frontend/src/hooks/useDrawing.ts
- frontend/src/hooks/usePanning.ts
- frontend/src/hooks/useUndoRedo.ts
- frontend/src/hooks/useZoom.ts
- 캔버스에 전 찍어서 선 그리기
- 점이 1개일 경우 점만 찍힘
- 점이 2개 이상일 경우 선으로 이어짐
- 마우스를 눌러서 캔버스 내에 그림들 이동 가능
- 마우스 휠을 이용하여 캔버스 확대 / 축소 구현
- undo redo 기능
#4 사용자가 지도에 자유롭게 선을 그을 수 있다
#201 undo 버튼을 누른다면 그렸던 최신 선의 하나가 지워진다
#202 redo 버튼을 누른다면 undo 했던 선의 하나가 복구된다
https://github.com/user-attachments/assets/648ced2d-f47c-459d-8a6a-807e7c98d029
- 페이지에서 ```<Linedrawer />```
> [FE][Feat] #4 : 캔버스에 선그리기, 이동, 확대/축소 훅

- frontend/src/component/BottomSheet/BottomSheet.tsx
- frontend/src/component/common/modal/Modal.tsx
- frontend/src/component/content/Content.tsx
- frontend/src/hooks/useBottomSheet.ts
- frontend/src/pages/Main.tsx
- 바텀시트의 높이를 2단계 대신 자유롭게 변경할 수 있게 변경
- 바텀시트 최저 높이 변경
- 불필요한 코드 삭제
- z-index 조절
#14 바텀시트 내부의 경로 목록 컴포넌트
https://github.com/user-attachments/assets/64754a80-d3ec-41ff-a017-9d2cc77a3133
> [FE][Feat] #14 : 바텀시트의 높이를 2단계 대신 자유롭게 변경할 수 있게 변경

- backend/src/middleware/authenticateJWT.js
- backend/src/routes/channelRouter.js
헤더의 JWT 토큰으로 사용자 검증 middleware 추가
---
- 사용자 검증 middleware 함수 구현
- 일부 api에 사용자 검증 middleware 추가
---
---
#219 
---
- 헤더에 token 넣지 않은 상태로 api 요청시 실패
- 헤더에 토큰 넣은 상태로 api 요청시 성공
> [BE][Feat] #219 : 헤더의 JWT 토큰으로 사용자 검증 middleware 추가

- frontend/src/component/canvas/Canvas.tsx
- frontend/src/component/canvas/CanvasWithMap.tsx
- frontend/src/component/maps/Map.tsx
- frontend/src/component/maps/NaverMap.tsx
- frontend/src/hooks/usePanning.ts
캔버스와 지도 연동
- 캔버스와 지도 이벤트 연동
- 캔버스에 그림이 그려진 상태로 지도와 같이 움직일 수 있도록 구현
#244
https://github.com/user-attachments/assets/8a934589-a99c-4c42-9bd5-05b935b15506
> [FE][Feat] #224 : 캔버스와 지도 연동

- backend/src/controllers/channelController.js
- backend/swaggerConfig.js
사용자별 채널 get api response 타입 수정
---
사용자별 채널 get api response 타입 수정
---
---
#230
---
> [BE][Feat] #230 : 사용자별 채널 get api response 타입 수정

- frontend/src/component/canvas/CanvasWithMap.tsx
- frontend/src/pages/GuestView.tsx
- frontend/src/pages/Main.tsx
Main 지도 출력 안되는 버그 수정
- `Main.tsx`에서 `Map` Component를 `CanvasWithMap`으로 수정
> [FE][Fix] #224 : Frontend 버그 수정

- frontend/src/component/maps/NaverMapSample.tsx
- frontend/src/pages/Main.tsx
위치 테스트를 위한 네이버 지도 샘플 코드 작성
네이버 지도 샘플 코드 추가
> [FE][Fix] #224 : 네이버 지도 샘플 코드 작성

- frontend/src/component/maps/Map.tsx
- frontend/src/component/maps/Map.types.ts
- frontend/src/component/maps/NaverMap.tsx
- frontend/src/component/maps/mapUtils.ts
- frontend/src/component/maps/naverMapUtils.ts
지도 컴포넌트 리팩토링
통합 과정에서 지나치게 스파게티 코드가 되어, 손쓰기 어려울 듯 해서 지도 컴퍼넌트 수정
#224
> [FE][Refactor] #224 : 지도 컴포넌트 리팩토링

- .github/workflows/ci.yml
- frontend/src/component/canvas/Canvas.tsx
- frontend/src/component/canvas/CanvasWithMap.tsx
- frontend/src/component/canvas/useEventHandlers.tsx
CanvasWIthMap을 이벤트 함수를 훅으로 분리
CanvasWithMap에 있는 이벤트 함수 로직을 훅으로 분리했다.
#224
https://github.com/user-attachments/assets/6c331502-e0d0-43f6-8934-f65458c64ce8
분리는 성공하였으나, 위와 같이 오동작하는 문제가 있음.
> [FE][Refactor] #224 : CanvasWithMap 이벤트 함수를 훅으로 분리

- frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
- frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
- frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapProviderForDraw.tsx
- frontend/src/lib/constants/mapConstants.ts
- frontend/src/lib/types/canvasInterface.ts
- frontend/src/pages/DrawRoute.tsx
지도-캔버스 연동된 화면 (보기 전용)
---
- 사용자 현재 위치 canvas에 띄우기
- 다른 사용자들 현재 위치 canvas에 띄우기
- 그려진 다른 게스트들의 출발점,도착점,경로 canvas에 띄우기
---
---
#258 
---
> [FE][Feat] #258 : 지도-캔버스 연동된 화면 (보기 전용)

- frontend/index.html
- frontend/src/App.css
- frontend/src/App.tsx
- frontend/src/index.css
- frontend/src/pages/Main.tsx
홈화면에 지도-캔버스 연동된 화면 노출
---
- 홈 화면에서 지도와 캔버스 연동된 지도 노출
- 사용자의 실시간 현재 위치 캔버스로 표시
- 화면까지 확대/축소, 스크롤되는 문제 해결
---
---
#260 
---
https://github.com/user-attachments/assets/2e63e7ae-a257-46f8-9a87-b7c5535d2afc
---
> [FE][Feat] #260 : 홈화면에 지도-캔버스 연동된 화면 노출

- backend/package.json
- backend/src/websocketServer.js
- docker-compose.yml
- frontend/Dockerfile
4주차 배포를 위한 세팅
---
- 4주차 배포를 위한 세팅 (dev 브랜치와 동일)
- (4주차 배포 당시 급하게 배포하느라 바로 dev 브랜치에서 작업했어서, backend 브랜치와 동기화시키기 위한 PR입니다.)
---
---
#242
---
> [BE][Chore] #242 : 4주차 배포를 위한 세팅

- frontend/src/api/dto/channel.dto.ts
- frontend/src/component/routebutton/RouteResultButton.tsx
- frontend/src/component/searchbox/SearchBox.tsx
- frontend/src/component/tooldescription/ToolDescription.tsx
- frontend/src/pages/AddChannel.tsx
- frontend/src/pages/DrawRoute.tsx
- createChannel API 연동
---
---
#241 
---
https://github.com/user-attachments/assets/dac3a5f3-0c86-4c4a-8e07-69a7b44ed3e3
---
- channelName 반영 오류가 있어 useEffect로 의존성 추가해 해결했습니다!
> [FE][Feat] #241 : createChannel API 연동 성공

- backend/Dockerfile
- docker-compose.yml
- frontend/Dockerfile
volumes로 app 디렉토리 공유하여 배포 문제 해결
---
- volumes로 app 디렉토리 공유하도록 변경
- node_modules는 충돌 때문에 volumes에서 제외
- frontend 컨테이너 backend에 의존
---
---
> [BE][Chore] volumes로 app 디렉토리 공유하도록 변경

- frontend/src/App.css
- frontend/src/component/common/loadingSpinner/LoadingSpinner.tsx
- frontend/src/pages/Main.tsx
지도 가져올 때 로딩 화면 추가 (로딩 스피너로 대체)
---
- 지도 가져올 때 로딩 화면 추가 (로딩 스피너로 대체)
- 홈 화면에서 지도 로딩 화면 적용
@effozen @leedongyull 님 바쁘지 않으실 때 지도 각 페이지에서 사용하실 때, 이 컴포넌트 사용해서 로딩 관련 로직 추가 부탁드립니다!
---
---
#274
---
---
> 지도 가져올 때 로딩 화면 추가 (로딩 스피너로 대체)

- frontend/src/App.css
- frontend/src/App.tsx
데스크탑 접속시 모바일 접속 유도
---
- 데스크탑 접속시 모바일 접속 유도
---
---
**설명**: 이 체크리스트는 PR 작성자가 스스로 점검할 수 있는 기준을 제시합니다. 코드가 빌드 오류 없이 작동하고, 테스트를 통과하며, 스타일 가이드를 따르고 있는지 확인하는 항목들입니다.
---
#286
---
---
> [FE][Feat] #286 : 데스크탑 접속시 모바일 접속 유도

- frontend/src/component/bottomsheet/BottomSheet.tsx
- frontend/src/pages/Main.tsx
- x 버튼 absolute로 변경
- login이 되어있지 않을 경우 바텀시트의 다른 부분을 클릭해도 로그인 모달이 열리게 변경
#59
> [FE][Feat] #59 : 바텀시트 전체에서 클릭시 로그인 모달 띄움

- frontend/src/component/common/loadingSpinner/LoadingSpinner.tsx
로딩 스피너 텍스트 제거
---
지도 로딩 될 때 `Loading map data...`라는 텍스트와 함께 로딩하고 있는데, 한국어로 표시해도 좋을 것 같다는 의견 존재,
한국어로 문구를 수정하거나 아예 텍스트 제거하는 방안으로 검토 필요
https://github.com/boostcampwm-2024/web28-DDara/pull/276#discussion_r1858504878
---
---
#306
---
> [FE][Refactor] #306 : 로딩 스피너 텍스트 제거

- frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
- frontend/src/component/routebutton/RouteResultButton.tsx
- 마커 설정 시 줌 기능 구현
- 검색으로 찍은 마커, 플로팅 버튼으로 찍은 마커 둘다 적용
- 출발지, 도착지 모두 보이게 화면 확대
---
---
#314 
---
https://github.com/user-attachments/assets/69aaf067-8aad-4d7c-8a2d-b231190155ec
- 검색, 직접 설정 둘 다 화면 확대
- 만약 두 마커가 모두 찍혀있다면 좌표 거리 계산하여 화면 확대
---
- GPT가 계산식 만들어줘서 useEffect로 구현했습니다!!
- 자세한 수치는 옆에 콘솔 찍어보면서 노가다 했습니다..ㅎㅎ
---
> [FE][Feat] #314 : 마커 설정 시 줌 기능 구현

- frontend/src/hooks/getUserLocation.ts
현재 위치 추적이 실시간을 되지 않는 문제 해결
---
- geolocation API의 watchPosition 사용으로 변경
- 나의 현재 위치 실시간 반영
- 다른 사용자의 현재 위치 실시간 반영
---
---
#321 
---
위도/경도를 이렇게 임의로 조작해서, 이 상태를 모바일 (다른 디바이스)에서도 잘 받아오는지 테스트 진행했습니다.
https://github.com/user-attachments/assets/ed4a7d0c-e249-495f-9563-eb3aaeef0020
---
> [FE][Feat] #321 : 현재 위치 추적이 실시간을 되지 않는 문제 해결

- frontend/src/component/bottomsheet/BottomSheet.tsx
- frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
- frontend/src/component/content/Content.tsx
- frontend/src/component/zoomslider/ZoomSlider.tsx
- frontend/src/hooks/useRedraw.ts
- frontend/src/pages/Main.tsx
- 로그인
- 왼쪽 상단 햄버거 버튼 대신 로그아웃 버튼으로 구현
- 로그아웃 버튼에 로그아웃이라고 텍스트 넣기
- 지도
- 지도 확대 축소 슬라이드바 줌 지도 사용하는 모든 곳에 넣기
- 아이콘 이미지 키우기
- 바텀시트 
- 바텀시트 맨 아래 컨탠츠가 버튼에 가려지는 문제 해결
- 바텀시트 최초 높이 변경 및 로그인 유도 텍스트 위로 올리기
- 바텀시트내에 컨텐츠 클릭 범위 전체로 변경
#14 
https://github.com/user-attachments/assets/d3b22817-e4c3-45be-a717-a1de111368ed
> [FE][Feat] : 바텀시트, 메인페이지 QA 작업

- frontend/src/component/onBoarding/Onboarding.tsx
온보딩 페이지 height 문제 해결
---
- 온보딩 페이지 height 문제 해결
---
---
#357
---
- 이전 화면
https://github.com/user-attachments/assets/c00f9d53-2ab7-46d2-8eb9-ae6dd79dd2f2
- 개선 작업 후 화면
- 
https://github.com/user-attachments/assets/ebc19976-5c50-4124-ae68-687603ac1b21
> [FE][Fix] #357 : 온보딩 페이지 height 문제 해결

- frontend/src/hooks/useRedraw.ts
- hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결
---
- hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결
---
---
#394
---
- 기존 문제 화면
- 해결 후 화면
> [FE][Fix] #394 : hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결

- frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
- frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx
- frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapProviderForDraw.tsx
- frontend/src/component/zoomslider/ZoomSlider.tsx
- frontend/src/lib/constants/mapConstants.ts
지도가 주기적으로 재렌더링되는 문제 해결, 기본 줌 레벨 값 변경
---
-  지도가 주기적으로 재렌더링되는 문제 해결
- 기본 줌 레벨 값 변경
- 기본 줌 레벨 값 변수화
- 불필요한 주석 제거
---
---
#430 
-------
- 발생 문제
https://github.com/user-attachments/assets/33f8be75-00ab-4329-ae12-a1011360e196
> [FE][Fix] #430 : 지도가 주기적으로 재렌더링되는 문제 해결, 기본 줌 레벨 값 변경

- frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapProviderForDraw.tsx
- frontend/src/component/searchbox/SearchBox.tsx
- frontend/src/component/zoomslider/ZoomSlider.tsx
- frontend/src/pages/DrawRoute.tsx
- 검색창에서 이벤트 버블링 방지
- zoomslider에서 이벤트 버블링 방지
- 경로그리기 페이지 높이가 화면 밖으로 넘어가는 문제 해결
#258 
https://github.com/user-attachments/assets/8c9f949a-07f8-439a-a253-e6bf4cdd282a
> [FE][Feat] : 검색창,zoomslider에서 이벤트 버블링 방지

- frontend/src/api/channel.api.ts
- frontend/src/component/bottomsheet/BottomSheet.tsx
- frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
- frontend/src/component/setCurrentLocationButton/SetCurrentLocationButton.tsx
- frontend/src/pages/AddChannel.tsx
- frontend/src/pages/DrawRoute.tsx
- frontend/src/pages/GuestView.tsx
- frontend/src/pages/Main.tsx
- frontend/vite.config.ts
- 현재 위치로 이동 버튼 구현
- 바텀시트 높이에 맞도록 위치
- add-channel footer 오류 수정
---
---
#429 
---
---
> [FE][Feat] 현재 위치로 이동 버튼 구현 및 add-channel footer 사라지지 않도록 구현

- frontend/src/hooks/getUserLocation.ts
- frontend/src/pages/GuestView.tsx
- guestView에서 방향 받아오지 못하는 문제 해결
---
- guestView에서 방향 받아오지 못하는 문제 해결
---
> [FE][Fix] QA

- frontend/src/hooks/useRedraw.ts
- frontend/src/pages/AddChannel.tsx
- 유저 캐릭터 마커 위로 수정
- 유저 방향 수정
---
---
---
> [FE][Feat] 사용자 마커 및 패스 위로 올림, 방향 수정
