README.md
- 링크에 팀 위키 추가
- 링크에 회의록, 그라운드 룰 등 팀 노션과 중복되는 링크 제거
=> [Docs] : readme 링크 수정

backend/package.json, backend/src/index.js, backend/src/routes/example.js, backend/swaggerConfig.js
- swagger 설치
- 예시 코드 작성
- 예시 코드 동작 확인
=> [BE][Docs] #82 : swagger 설치 및 예시 적용

pnpm-lock.yaml
---
name: pnpm-lock 파일 변경 업데이트
about: swagger 설치
title: 'pnpm-lock 파일 변경 업데이트'
labels: ''
assignees: '@happyhyep'
---
pnpm-lock 파일 변경 업데이트
---
- pnpm-lock 파일 변경 업데이트
=> [ENV][BE] #82 : swagger 설치

docs/docusaurus/docs/study/test.mdx
- 큰 변경사항 없이 docs를 vercel로 배포하는 것에 대한 테스트입니다.
- conflict 나는 것을 막기 위해서 merge합니다.
=> [ENV][Docs] #1 : docs 배포 테스트

README.md, docs/docusaurus/README.md, docs/docusaurus/package.json, docs/docusaurus/tsconfig.json, eslint.config.mjs, pnpm-lock.yaml
- ESLint 수정 및 README.md 문서 링크 수정
=> [ENV][Fix] #1 : eslint 및 ReadMe.md 수정

frontend/tailwind.config.js
---
tailwind 컬러 및 폰트 세팅
---
---
**설명**: 이 체크리스트는 PR 작성자가 스스로 점검할 수 있는 기준을 제시합니다. 코드가 빌드 오류 없이 작동하고, 테스트를 통과하며, 스타일 가이드를 따르고 있는지 확인하는 항목들입니다.
---
#130 해결
---
**설명**: 이 PR과 관련된 이슈 번호를 링크하여 리뷰어가 관련된 문제나 요청 사항을 쉽게 참고할 수 있도록 합니다. 이를 통해 이슈와 PR을 연결하여 작업의 목적을 명확히 할 수 있습니다.
---
---
**설명**: UI 변경 사항이 포함된 경우, 변경된 화면을 시각적으로 보여주기 위해 스크린샷이나 동영상을 첨부하면 도움이 됩니다. 리뷰어는 화면 변경 사항을 바로 확인할 수 있어 코드 리뷰가 더 효과적입니다.
---
=> [CHORE][FE] #130 : tailwind 컬러 및 폰트 세팅

eslint.config.mjs, frontend/src/App.tsx, frontend/src/component/maps/Map.tsx, frontend/src/component/maps/NaverMap.tsx, frontend/src/utils/maps/naverMap/setNaverMapObj.ts
지도 위에 브라우저 출력 기능 구현
- 지도 API 컴포넌트 추가
#107 
- 추후 추가 예정 (단, 단순 API 불러오는거라 테스트코드는 필요 없고, 스토리북 작성 예정)
=> [FE][Feat] #108 : 네이버 지도 API 브라우저에 출력할 수 있는 컴포넌트 구현

backend/src/routes/authRouter.js, backend/swaggerConfig.js
로그인 api swagger 문서 작성 
---
---
=> [BE][Feat] : #42 : 로그인 api swagger 문서 작성 

backend/src/controllers/channelController.js, backend/src/repositories/channelRepository.js, backend/src/routes/channelRouter.js, backend/src/services/channelService.js, backend/swaggerConfig.js
- 채널 id로 채널 정보, guest 정보 get API에 대한 swagger 문서 추가
- 채널 id로 채널 정보, guest 정보 get API 구현
---
- 채널 id로 채널 정보, guest 정보 get API에 대한 swagger 문서 추가
- 채널 id로 채널 정보, guest 정보 get API 구현
---
---
#45 
---
---
=> [BE][Feat] #45 : 채널 id로 채널 정보, guest 정보 get API 구현

backend/src/controllers/channelController.js, backend/src/repositories/channelRepository.js, backend/src/routes/authRouter.js, backend/src/routes/channelRouter.js, backend/src/services/channelService.js, backend/swaggerConfig.js
- guest id로 guest 정보 get API에 대한 swagger 문서 추가
- guest id로 guest 정보 get API 구현
- swagger 문서 세팅 수정
---
- guest id로 guest 정보 get API에 대한 swagger 문서 추가
- guest id로 guest 정보 get API 구현
- swagger 문서 세팅 수정
---
---
#46 
---
---
=> [BE][Feat] #46 : guest id로 guest 정보 get API 구현

backend/src/controllers/authController.js, backend/src/controllers/channelController.js, backend/src/repositories/channelRepository.js, backend/src/routes/channelRouter.js, backend/src/services/channelService.js, backend/swaggerConfig.js
- user id로 해당 user가 생성한 channel 정보 가져오기 API에 대한 swagger 문서 추가
- user id로 해당 user가 생성한 channel 정보 가져오기 API 구현
- API 형식 통일
---
- user id로 해당 user가 생성한 channel 정보 가져오기 API에 대한 swagger 문서 추가
- user id로 해당 user가 생성한 channel 정보 가져오기 API 구현
- API 형식 통일
---
---
#43 
---
---
=> [BE][Feat] #43 : user id로 해당 user가 생성한 channel 정보 가져오기 API 구현

frontend/src/component/linedrawer/Linedrawer.tsx, frontend/src/pages/DrawRoute.tsx
- DrawRoute 페이지 초안
- 선그리기 기능 (LineDrawer) 초안
- LineDrawer
- canvas를 지도의 크기에 딱 맞게 하는 함수 추가 예정
- 지우개 기능 추가 예정
- DrawRoute 페이지
- Header 완성시 Header로 교체
---
https://github.com/user-attachments/assets/2fc77f6d-00db-403d-bf33-16296409a123
=> [FE][Feat] #4 : DrawRoute 페이지 초안

Jenkinsfile
- jenkinsfile 파일 작성
---
- jenkinsfile 파일 작성
---
---
#166 
---
=> [BE][Chore] #166 : jenkinsfile 세팅

frontend/src/component/header/HeaderBackButton.tsx, frontend/src/component/layout/Layout.tsx, frontend/src/component/layout/enumTypes.ts, frontend/src/component/layout/footer/Footer.tsx, frontend/src/component/layout/footer/LayoutFooter.tsx, frontend/src/component/layout/footer/LayoutFooterProvider.tsx, frontend/src/component/layout/header/LayoutHeaderProvider.tsx, frontend/src/component/linedrawer/Linedrawer.tsx, frontend/src/pages/AddChannel.tsx, frontend/src/pages/DrawRoute.tsx, frontend/src/pages/Main.tsx, frontend/tailwind.config.js
- add-chennel, main, drawroute 페이지 헤더 및 푸터 적용
- footer 형식 변경
- 페이지 이동 연결
- 뒤로가기 시 context 초기화
- 사용자 추가 로컬스토리지로 유지 (추후 살짝 변경 필요)
- 자잘한 디자인 변경
---
---
#106 
---
--- 
---
현재 두 컴포넌트 모두 absolute 형태로 겹쳐있음.
footer를 Bottomsheet 안으로 넣고 싶으나 구조를 변경해야해서 생각이 더 필요할 것 같음
- 뒤로가기 버튼이 Navigate(-1)의 형태로 되어있어 뒤로가기 할 때, Context 충돌 발생  
- 
> ex) main에서 좌측 사이드 바 버튼과 뒤로가기 충돌
> 경로설정 페이지에서 뒤로가기 하면 소제목과 제목 그대로 넘어옴
등등
- 이를 우선 resetContext 함수를 만들어 뒤로가기 할 때마다 초기화시켜주는 방식으로 변경 (다른 방법으로 변경해야 할 수도 있음)
```
const { resetFooterContext } = useContext(FooterContext);
const { resetHeaderContext } = useContext(HeaderContext);
const handleHeaderBackButtonClick = () => {
if (window.history.length > 1) {
resetFooterContext();
resetHeaderContext();
navigate(-1);
} else {
navigate('/');
}
};
```
```
const resetFooterContext = () => { …
```
=> [FE][Feat] #106 : addChannel 등 여러 페이지 수정 및 Footer Context 형식으로 변경

backend/src/controllers/authController.js, backend/src/controllers/channelController.js, backend/src/dto/errorResponse.dto.js, backend/src/dto/response.dto.js, backend/src/routes/authRouter.js, backend/src/routes/channelRouter.js, backend/src/services/channelService.js
백엔드 응답/에러 처리 공통화
---
- 공통 응답 dto 생성
- 공통 에러 dto 생성
- 에러 핸들러 생성
- api 응답 dto 적용
---
---
#225 
---
=> [BE][Refactor] #225 : 백엔드 응답/에러 처리 공통화

frontend/src/index.css
폰트 안되는 이슈 해결
---
폰트 안되는 이슈 해결
---
---
#155 
---
- 수정 전 화면
- 수정 후 화면
=> [FE][Fix] #155 : 폰트 적용 안되는 이슈 해결

frontend/src/api/channel.api.ts, frontend/src/api/dto/channel.dto.ts
채널 생성 api 연동
---
채널 생성 api 연동
---
---
#226
---
=> [FE][Feat] #226 : 채널 생성 api 연동

frontend/src/api/auth.api.ts, frontend/src/api/dto/auth.dto.ts, frontend/src/component/authmodal/AuthModal.tsx
- 회원가입 api 연동
---
- 회원가입 api 연동
---
---
#222 
---
---
=> [FE][Feat] #222 : 회원가입 api 연동

eslint.config.mjs, frontend/package.json, frontend/src/component/maps/NaverMapSample.tsx, frontend/src/constants.ts, frontend/src/pages/Main.tsx
Main.tsx 화면에서 4주차 데모를 위한 실시간 현재 위치 받아오는 기능 추가
---
- Main.tsx 화면에서 보이는 지도 temp 데이터
- 사용자, 다른 사용자 모두 실시간 현재 위치 지도에 반영
- eslint 세팅 수정
- 배포를 위한 constants 변수 추가
=> [FE][Feat] Main.tsx 화면에서 4주차 데모를 위한 실시간 현재 위치 받아오는 기능 추가

frontend/src/component/linedrawer/Linedrawer.tsx, frontend/src/component/maps/Canvas.tsx, frontend/src/component/maps/MapCanvas.tsx, frontend/src/hooks/useFloatingButton.ts, frontend/src/hooks/useUndoRedo.ts, frontend/src/lib/constants/canvasConstants.ts, frontend/src/lib/types/canvasInterface.ts, frontend/src/pages/DrawRoute.tsx, frontend/src/pages/Main.tsx
채널 추가 화면 지도-캔버스 연동 화면 표시
---
- 사용하지 않는 파일 제거
- 채널 추가 화면에서 지도-캔버스 연동된 화면 표시
---
---
#253
---
@leedongyull 동율님 혹시 add-channel 페이지에서, 밑에 footer 버튼이 뜨지 않는 경우가 있는데 (특히 새로고침 하면) 작업하실 때 확인 부탁드립니다!
아까 이야기했던 처음 접속시 플로팅버튼 기본으로 띄워두는 등 간단한 작업은 제가 해뒀습니다! api 연동해주시면 될 것 같아요!
=> [FE][Feat] #253 : 채널 추가 지도-캔버스 연동 화면 표시

frontend/src/api/auth.api.ts, frontend/src/api/channel.api.ts, frontend/src/component/common/dropdown/DropdownItem.tsx, frontend/src/component/header/HeaderDropdown.tsx, frontend/src/component/layout/header/LayoutHeader.tsx, frontend/src/pages/HostView.tsx, frontend/src/types/channel.types.ts
통신 로직 및 받아온 데이터 드랍다운에 반영
- API에서 res.data로 수정
- API로 받아온 정보를 바탕으로 드랍다운과 화면에 보여지도록 출력
- channel uuid 별로 다른 정보를 가져오게 수정
#112 
https://github.com/user-attachments/assets/eb772988-bc0a-4e7b-9ba9-391900685fcc
=> [FE][Feat] #112 : 통신 로직 및 받아온 데이터 드랍다운에 반영

nginx.conf
4주차 배포를 위한 nginx 세팅
---
- 4주차 배포를 위한 nginx 세팅 (dev 브랜치와 동일)
- (4주차 배포 당시 급하게 배포하느라 바로 dev 브랜치에서 작업했어서, backend 브랜치와 동기화시키기 위한 PR입니다.)
---
---
#242
---
=> [BE][Chore] #242 : 4주차 배포를 위한 nginx 세팅

backend/Dockerfile, docker-compose.yml, frontend/Dockerfile, nginx.conf
- FE 컨테이너 Workdir 생성 안되는 문제 해결
---
- FE, BE 모두 WORKDIR `frontend-app`, `backend-app`으로 각각 생성 후 `docker-compose.yml` 파일에서 volumes로 참조하도록 변경
---
---
=> [BE][Chore] FE 컨테이너 Workdir 생성 안되는 문제 해결

nginx.conf
- nginx에서 react 앱의 모든 url을 index.html로 리다이렉트
---
- nginx에서 react 앱의 모든 url을 index.html로 리다이렉트
---
---
#266 
---
=> [BE][Chore] #266 : nginx에서 react 라우터와 호환되도록 수정

backend/src/repositories/channelRepository.js, backend/swaggerConfig.js
사용자의 채널 리스트 가져올 때 게스트 인원수도 가져오기
---
- 사용자의 채널 리스트 가져올 때 게스트 인원수도 가져오기 (API 수정)
- swagger 문서 수정
---
---
#271
---
---
=> [BE][Feat] #271 : 사용자의 채널 리스트 가져올 때 게스트 인원수도 가져오기

frontend/src/api/dto/auth.dto.ts, frontend/src/component/authmodal/AuthModal.tsx, frontend/src/component/common/modal/ModalInput.tsx
- DTO 구조 수정
- 모달 input창의 pw 입력칸에는 type password로 변경
```ts
export class LoginResEntity {
data: {
token: string | undefined;
userId: string | undefined;
} = {
token: undefined,
userId: undefined,
};
}
```
에서
```ts
export class LoginResEntity {
token: string | undefined;
userId: string | undefined;
}
```
로 변경
#59
=> [FE][Fix] #59 : DTO 구조 수정 및 pw input type 수정

frontend/src/App.css
데스크탑 접속시 모바일 접속 유도 병합 과정 충돌 해결
---
- 병합 과정 `{` 없어지는 문제 발생, 해결
죄송합니다.... 배포때문에 급하게 머지하느라 괄호 날리고 머지해버렸네요..........
---
---
#286
---
=> [FE][Feat] #286 : 데스크탑 접속시 모바일 접속 유도 병합 과정 충돌 해결

frontend/src/api/dto/channel.dto.ts
- build오류 없앴습니다!
---
---
- guestEntity를 req,res용으로 분리하였습니다 (id 때문에)
=> [FE][Feat] build 오류 제거

frontend/src/lib/constants/commonConstants.ts
- 백엔드 api 주소 변경
---
백엔드 api 주소가 :3001로 올라가있던 문제 해결
---
---
#295
---
=> [FE][ENV] #295 : 백엔드 api 주소 변경

backend/src/repositories/channelRepository.js, backend/swaggerConfig.js
채널 get api 응답 형식에 location title 항목 추가
---
- 채널 get api 응답 형식에 location title 항목 추가
- swagger 문서 수정
---
---
#298 
---
=> [BE][Feat] #298 : 채널 get api 응답 형식에 location title 항목 추가

eslint.config.mjs, frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx, frontend/src/component/canvasWithMap/canvasWithMapforDraw/MapCanvasForDraw.tsx, frontend/src/component/common/alert/Alert.tsx, frontend/src/routes/IndexRoutes.tsx, frontend/src/routes/RequireAuth.tsx
로그인해야 접속할 수 있는 url 접속시 접속이 불가능하도록 차단
---
- 로그인해야 접속할 수 있는 url 접속시 메인 화면으로 리다이렉트
- alert를 띄어서 n초 뒤에 메인 화면으로 리다이렉트 (n초 동안의 progress bar 애니메이션 적용)
---
----
#302 
---
=> [FE][Feat] #302 : 로그인해야 접속할 수 있는 url 접속시 접속이 불가능하도록 차단

frontend/src/pages/Register.tsx, frontend/src/pages/UserRoute.tsx, frontend/src/routes/IndexRoutes.tsx
사용하지 않는 routes 및 파일 제거
---
- 사용하지 않는 routes 및 파일 제거
---
---
#303
---
=> [FE][Refactor] #303 : 사용하지 않는 routes 및 파일 제거

frontend/src/component/common/alert/Alert.tsx, frontend/src/routes/RequireAuth.tsx
Alert progress bar 배포시 적용되지 않는 문제 해결
---
- Alert progress bar 배포시 적용되지 않는 문제 해결
- Alert 띄우는 시간 변경
- 불필요한 로직 제거
---
---
#311
=> [FE][Fix] #311 : Alert progress bar 배포시 적용되지 않는 문제 해결

frontend/src/component/content/Content.tsx, frontend/src/component/routebutton/RouteResultButton.tsx, frontend/src/component/routebutton/RouteSettingButton.tsx, frontend/src/pages/AddChannel.tsx, frontend/src/pages/ChannelInfoPage.tsx, frontend/src/pages/DrawRoute.tsx, frontend/src/routes/IndexRoutes.tsx
- 스타일 변경
- channel Info에서 전역상태 안쓰도록 교체
- update-channel -> channelInfoPage로 페이지 명 변경
- 색상 값 하드코딩으로 넘겨주도록 변경
---
---
- alert 메시지 정렬
https://github.com/user-attachments/assets/425e7b63-11ec-43bd-941b-895b21bba42f
- 채널 상태 관리
---
=> [FE][Feat] #241 : 스타일 변경 및 채널 상태 로직 변경

frontend/src/component/IconGuide/GuestMarker.tsx, frontend/src/pages/GuestView.tsx, frontend/src/pages/HostView.tsx
HostView, GuestView 피젯스피너 추가
- HostView, GuestView 피젯스피너 추가
#301 
https://github.com/user-attachments/assets/87288c62-33d7-4903-9698-bc615279e2c5
=> [FE][Feature] #301 : HostView, GuestView 피젯스피너 추가

backend/src/websocketServer.js
hostview, guestview에서 접속한 경우 각각에 대한 socket 설정 수정
---
- hostview에서 socket으로 guest들의 실시간 위치 정보만 받아오기
- guestview에서는 socket으로 본인의 위치를 보내는 역할
---
---
#329 
---
=> [BE][Fix] #329 : hostview, guestview에서 접속한 경우 각각에 대한 socket 설정 수정

frontend/src/api/channel.api.ts, frontend/src/api/dto/channel.dto.ts, frontend/src/component/common/InputBox.tsx, frontend/src/component/content/Content.tsx, frontend/src/component/layout/constant/HeaderConst.ts, frontend/src/component/routebutton/RouteResultButton.tsx, frontend/src/context/UserContext.tsx, frontend/src/pages/AddChannel.tsx, frontend/src/pages/AddGuestPage.tsx, frontend/src/pages/ChannelInfoPage.tsx, frontend/src/pages/DrawRoute.tsx, frontend/src/routes/IndexRoutes.tsx, frontend/src/utils/mapping/HeaderMapping.ts
- addGuestPage UI 구현
- addGuest api 추가
- addGuest api 연동
---
---
#319 
---
https://github.com/user-attachments/assets/c1d662f3-d676-436d-b332-3cc7bceab203
---
- 수정하기 기능을 만들다 channel에 들어있는 guest를 호출하던 중 index가 없어 사용자 2,3,1의 순서 등 섞여서 나옴
- guest 내에서 index 역할을 할 것을 찾다가 마커 스타일로 구현...
- 너무 야매 같지만 딱히 방법이 없어서 어떻게 해야할 지 모르겠습니당
```
"guest": {
"name": "string",
"start_location": {
"lat": 0,
"lng": 0
},
"end_location": {
"lat": 0,
"lng": 0
},
"path": [
{
"lat": 0,
"lng": 0
}
],
"marker_style": {
"color": "string"
}
```
ex)
```
const markerColors: { [key: number]: string } = {
1: '#B4D033',
2: '#22A751',
3: '#2722A7',
4: '#8F22A7',
5: '#A73D22',
};
// 여기서 MarkerStyle이 #B4D033이면 index 1번으로..
```
- 또한 수정 과정에서 라우터 문제 때문에 테스트 해보다가 채널이 너무 많아져 한번 정리할 필요가 있을 것 같습니다!
---
=> [FE][Feat] addGuest 페이지 및 기능 구현

frontend/src/routes/AlertUndefinedURL.tsx, frontend/src/routes/IndexRoutes.tsx
정의되지 않은 경로에 대한 예외 처리 로직 구현
Router Path가 맞지 않을 경우 정해진 화면 출력
예외로 경고해주고, 자동으로 Main Redirection
#324 
https://github.com/user-attachments/assets/3a1b3c89-e3da-48c5-b908-243c2c4f473e
=> [FE][Feat] #324 : 정의되지 않은 경로에 대한 예외 처리

frontend/src/hooks/useFloatingButton.ts, frontend/src/routes/AlertUndefinedURL.tsx, frontend/src/routes/IndexRoutes.tsx
Floating Button 항상 열려있게 수정
- Floating Button 항상 열려있게 수정 + 열려있을 때 아이콘이 가이드가 되도록 수정
#328 
Uploading 화면 기록 2024-11-28 오후 6.55.45.mov…
=> [FE][Feature] #328 : Floating Button 항상 열려있게 수정

frontend/src/component/header/HeaderDropdown.tsx, frontend/src/hooks/useFloatingButton.ts, frontend/src/routes/AlertUndefinedURL.tsx, frontend/src/routes/IndexRoutes.tsx
게스트 한명만 있는 채널 접속시 기본적으로 선택되지 않는 문제 해결
- HeaderDropdown 옵션 수정
#333 
https://github.com/user-attachments/assets/0b13812b-a597-4171-823d-fc8e25070f5d
=> [FE][Feature] #333 : 게스트 한명만 있는 채널 접속시 기본적으로 선택되지 않는 문제 해결

backend/src/websocketServer.js
hostview, guestview에 대한 websocket 오류 발생 해결
---
- hostview에서 socket으로 guest들의 실시간 위치 정보만 받아오기
- guestview에서는 socket으로 본인의 위치를 보내는 역할
---
---
#337 
---
=> [BE][Fix] #337 : hostview, guestview에 대한 websocket 오류 발생 해결

frontend/src/component/searchbox/SearchBox.tsx
- 배포를 위한 검색 API URL 수정
---
- 배포를 위한 검색 API URL 수정 했습니다
- 
---
---
=> [FE][Fix] 배포를 위한 검색 API URL 수정

backend/src/websocketServer.js
5주차 6차 배포 (BE)
---
websocket 세팅 변경
---
---
=> 5주차 6차 배포 (BE)

nginx.conf, package.json
storybook 배포
---
- package.json 명령어 추가
- nginx.conf 파일 수정
---
---
#363
---
=> [FE][Feat] #363 : storybook 배포

frontend/src/pages/GuestView.tsx, frontend/src/pages/HostView.tsx, frontend/src/routes/IndexRoutes.tsx, frontend/src/utils/error/ErrorBoundary.tsx, frontend/src/utils/error/RouterErrorHandler.tsx
잘못된 링크로 들어왔을 경우 메인 페이지로 리다이렉션 구현
- 에러 리다이렉션 구현
#376 
https://github.com/user-attachments/assets/a21dd910-f693-4638-922a-2562b1a247fa
=> [FE][Feat] #376 : 잘못된 링크로 들어왔을 경우 메인 페이지로 리다이렉션 구현

frontend/src/hooks/useRedraw.ts, frontend/src/pages/HostView.tsx
호스트뷰에서 마커 색상 검은색으로 통일되는 문제 해결
---
호스트뷰에서 마커 색상 검은색으로 통일되는 문제 해결
---
---
#386
=> [FE][Fix] #386 : 호스트뷰에서 마커 색상 검은색으로 통일되는 문제 해결

frontend/src/pages/HostView.tsx
HostView에서 유저 확인 시 유저의 현재 위치가 감춰지지 않는 문제 해결
---
HostView에서 유저 확인 시 유저의 현재 위치가 감춰지지 않는 문제 해결
---
---
#350 
---
=> [FE][Fix] #350 : HostView에서 유저 확인 시 유저의 현재 위치가 감춰지지 않는 문제 해결

frontend/src/pages/GuestView.tsx, frontend/src/pages/HostView.tsx
HostView에서 유저 확인 시 유저의 현재 위치가 감춰지지 않는 문제 해결 
---
- HostView에서 유저 확인 시 유저의 현재 위치가 감춰지지 않는 문제 해결 
- guest의 위치 초기값 받아오지 못하는 문제 해결
---
---
#350
---
=> [FE][Fix] #350 : [FE][Fix] HostView에서 유저 확인 시 유저의 현재 위치가 감춰지지 않는 문제 해결 

frontend/src/pages/GuestView.tsx
- guest의 위치 초기값 받아오지 못하는 문제 해결
---
- guest의 위치 초기값 받아오지 못하는 문제 해결
---
---
#350
---
=> [FE][Fix] guest의 위치 초기값 받아오지 못하는 문제 해결

frontend/src/pages/GuestView.tsx, frontend/src/pages/HostView.tsx
- guest의 위치 초기값 받아오지 못하는 문제 해결
---
- guest의 위치 초기값 받아오지 못하는 문제 해결
---
---
#350
---
=> [FE][Fix] guest의 위치 초기값 받아오지 못하는 문제 해결 

frontend/src/hooks/useRedraw.ts
출발지/도착지 마커 y좌표 내리기
---
출발지/도착지 마커 y좌표 내리기
---
---
#396 
---
=> [FE][Fix] #396 : 출발지/도착지 마커 y좌표 내리기

frontend/src/hooks/useRedraw.ts, frontend/src/lib/constants/canvasConstants.ts, frontend/src/pages/GuestView.tsx
canvas 캐릭터와 마커에 대한 UI 개선 작업
---
- 게스트뷰의 path color 변경
- 마커, path color 변경
- 캐릭터와 마커 크기 변경
- 마커와 캐릭터 zindex 변경
---
---
#397
---
- 작업 전 UI 상황
=> [FE][Fix] #397 : canvas 캐릭터와 마커에 대한 UI 개선 작업

frontend/src/hooks/getUserLocation.ts
실시간 방향 받아오기
---
실시간 방향 받아오기 (ios에서 권한 허용)
---
---
#400 
---
=> [FE][Feat] #400 : 실시간 방향 받아오기

frontend/src/hooks/getUserLocation.ts, frontend/src/hooks/useRedraw.ts, frontend/src/lib/constants/canvasConstants.ts, frontend/src/pages/AddGuestPage.tsx, frontend/src/pages/HostView.tsx
---
hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결
---
- hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결
- 불필요한 콘솔 제거
- 불필요한 주석 제거
---
---
#394
=> [FE][Fix] #394 : hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결

frontend/src/hooks/getUserLocation.ts, frontend/src/hooks/useRedraw.ts, frontend/src/lib/constants/canvasConstants.ts, frontend/src/pages/AddGuestPage.tsx, frontend/src/pages/GuestView.tsx, frontend/src/pages/HostView.tsx
---
불필요한 콘솔, 주석 제거
---
- hostview의 게스트 이미지 아래 네온에 테두리 칠해져있는 문제 해결
- 불필요한 콘솔 제거
- 불필요한 주석 제거
---
---
#394
=> [FE][Fix] 불필요한 콘솔, 주석 제거

frontend/src/component/content/Content.tsx, frontend/src/pages/Main.tsx
- 채널을 새로 만들면 바텀시트에 업데이트
- 시간이 현재 한국 시간과 맞지 않는 문제해결
#411
=> [FE][Feat] #411 : 채널을 새로 만들면 바텀시트에 업데이트

backend/src/controllers/channelController.js, backend/src/repositories/channelRepository.js, backend/src/routes/channelRouter.js, backend/src/services/channelService.js, frontend/src/api/channel.api.ts, frontend/src/api/dto/channel.dto.ts, frontend/src/component/confirm/Confirm.tsx, frontend/src/component/content/Content.tsx, frontend/src/pages/Main.tsx
채널삭제 로직 구현
- `Main.tsx`의 바텀시트에서 드랍다운에 있는 삭제 버튼 클릭시 채널이 삭제되도록 로직 구현
#416
=> [FE][Feature] #416 : 채널삭제 로직 구현

frontend/src/component/common/types.ts, frontend/src/component/header/HeaderLayout.tsx, frontend/src/component/layout/constant/HeaderConst.ts, frontend/src/component/routebutton/RouteResultButton.tsx, frontend/src/component/routebutton/RouteSettingButton.tsx, frontend/src/component/searchbox/SearchBox.tsx, frontend/src/pages/AddChannel.tsx, frontend/src/pages/AddGuestPage.tsx, frontend/src/pages/ChannelInfoPage.tsx
- 사용자 이름 설정 가능하도록 변경
- alert에도 사용자 이름 들어가도록 변경
- 검색 결과 크기수정 및 정렬
- Header key값 오류 해결
- floatingbutton 아이콘 수정 및 순서 변경
---
---
#360 
---
https://github.com/user-attachments/assets/764a4706-707a-4a2a-9517-ff97dd4972f7
---
=> [FE][Feat] 사용자 이름 설정 가능하도록 변경 및 자잘한 거 수정

frontend/src/App.css, frontend/src/index.css
일부 ios에서 터치 이벤트 제대로 동작하지 않는 문제 해결
---
- 일부 ios(아이폰 12)에서 터치 이벤트 제대로 동작하지 않는 문제 해결
- 아이폰 12 환경에서 테스트
---
---
#433
---
문제 상황
https://github.com/user-attachments/assets/e33d15a0-eb3d-49c4-a055-d65c385f79ab
=> [FE][Fix] #433 : 일부 ios에서 터치 이벤트 제대로 동작하지 않는 문제 해결

frontend/src/hooks/useRedraw.ts
- 방향 로직 수정
---
- 방향 로직 수정
---
---
#436 
---
=> [FE][Fix] #436 : 방향 맞지 않는 문제 해결

frontend/src/component/bottomsheet/BottomSheet.tsx, frontend/src/pages/Main.tsx
- 비로그인시 글자가 페이지 밖으로 벗어나는 문제 해결
- 바텀시트의 content부분의 공간이 많이 남는 css 수정
[아래와 같은 문제를 발견하고 수정]
https://github.com/user-attachments/assets/33d43218-a9a7-4dcc-9da4-f7ce1dd314c7
[수정화면]
=> [FE][Fix] : 비로그인시 글자가 페이지 밖으로 벗어나는 문제 해결

frontend/src/hooks/useRedraw.ts
- 클러스터 색상 guest 색상에 맞도록 변경
---
---
#360 
---
=> [FE][Feat] QA : 클러스터 색상 변경

frontend/src/pages/Main.tsx
가이드 보기 버튼 메인에 추가
- 가이드보기 버튼 추가
#438 
https://github.com/user-attachments/assets/92af76d9-986f-4410-882a-ac40093d5024
=> [FE][Feat] #438 : 가이드 보기 버튼 메인에 추가

frontend/src/component/searchbox/SearchBox.tsx, frontend/src/component/zoomslider/ZoomSlider.tsx
검색창,zoomslider에서 터치 이벤트 스크롤 문제 해결
---
- 검색창에서 터치로 스크롤되지 않는 문제 해결
- zoomslider에서 터치로 슬라이드되지 않는 문제 해결
---
---
#411 
---
---
=> [FE][Fix] #441 : 검색창,zoomslider에서 터치 이벤트 스크롤 문제 해결

frontend/src/component/bottomsheet/BottomSheet.tsx, frontend/src/component/canvasWithMap/canvasWithMapForView/MapCanvasForView.tsx
- BottomSheet 이벤트 스크롤 문제 해결
---
- BottomSheet 이벤트 스크롤 문제 해결
---
---
#441
=> [FE][Fix] #441 : BottomSheet 이벤트 스크롤 문제 해결

frontend/src/pages/AddChannel.tsx
- userName 반영 안되는 오류 수정
---
---
=> [FE][Fix] userName 반영 안되는 오류 수정
